### ISSUE TITLE
Broken links in readme file

### ISSUE THREAD

**Issue by ravisha22** [hyperlight-dev/hyperlight#59]
Broken links in Readme file. Example, links titled “how Hyperlight works”, debugging Hyperlight etc are broken and link to non existent files. Please fix and link them to correct files. Edit: The readme file is under docs folder https://github.com/hyperlight-dev/hyperlight/tree/main/docs#further-reading and https://github.com/hyperlight-dev/hyperlight/tree/main/docs#for-developers

**Comment by ludfjig** [comment]
Thanks for the report! Indeed some links are broken, and we'll try to get these fixed soon.
